### ISSUE TITLE
Report more information on the ReportThrowablePanel 

### ISSUE THREAD

**Issue by jimmyMaci** [astrapi69/jaulp-wicket#32]
Hi there,

can you extend the ReportThrowablePanel to report more information. Like where the exception is occured i.e the Page, the user, the wicket model.

Cheers 
Jim

**Comment by astrapi69** [comment]
Hello Jim,

your invited to make this change request. Send a PR and i will merge it.

Regards
astrapi69

**Comment by astrapi69** [comment]
Hello Jim, i will close this issue, the requested feature is now provided.
