### ISSUE TITLE
There is almost no documentation...

### ISSUE THREAD

**Issue by PhantomYdn** [astrapi69/jaulp-wicket#7]

**Comment by astrapi69** [comment]
Hello @PhantomYdn,

your are right, we use this lib for our own websites and provide the code to the community. I want in the near future provide an extended documentation.

But if you want to see how the components are used, the most examples are in the example projects like jaulp.wicket.components.examples.

I try to follow the design pattern principles in the components.

The most components provide factory methods like described in the book wicket in action book. 
All actions calls have callback methods with the prefix on*.
All factory methods have the prefix new*.

**Comment by astrapi69** [comment]
Hi @PhantomYdn,
i have added now documentation to the project. I will close this issue for now.
